version: '3'
services:
  spe-mysql-container:
    image: mysql
    container_name: spe-mysql-container
    restart: always
    networks:
      - spe-network
    environment:
      MYSQL_DATABASE: "spe"
      MYSQL_ROOT_PASSWORD: "Password"
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - "~/spe-dp:/var/lib/mysql"

  spe-backend-container:
    image: "saurabh412/backendspe"
    container_name: spe-backend-container
    restart: always
    networks:
      - spe-network
    ports:
      - "9080:9080"
    depends_on:
      - spe-mysql-container

  spe-frontend-container:
    image: "saurabh412/frontendspe"
    container_name: spe-frontend-container
    restart: always
    networks:
      - spe-network
    ports:
      - "3000:3000"
    depends_on:
      - spe-backend-container

networks:
  spe-network:
    driver: bridge

volumes:
  spe-dp:
